### ISSUE TITLE
[KKListView example] Pull to refresh feature not showed after loadMore

### ISSUE THREAD

**Issue by j796160836** [KKBOX/android_kktoolkit#146]
Here is the step to reproduce,
1. Run the example
2. swipe down to the bottom (You can see the loadMore progress bar)
3. After the progress bar hide, swipe up to the top and try to pull refresh.

Expected result:
- Show up the pull to refresh UI and refresh it.

Actually result:
- Nothing showed up.

**Comment by danieldeng** [comment]
Hi Jonny,
You should call setAdapter() again to let KKListview know to reset state. 
(I know it's kind of weird caused you may just call adapter to notifyDataSetChanged() at the second time to refresh listview's data.)

**Comment by danieldeng** [comment]
We just fixed the sample code's bug in f11a2bf90cda02a6dc33d2dc416f3ab30019e574
Thanks your report.
