### ISSUE TITLE
[KKListView example] UI freezes when no network condition

### ISSUE THREAD

**Issue by j796160836** [KKBOX/android_kktoolkit#147]
Step to reproduce,
1. Run the KKListView example without internet.
2. Swipe down to the bottom (You can see the loadMore progress bar)

Expected result:

- Show up the no network dialog or hide it.

Actually result:

- UI freezes at the progressing state.

**Comment by danieldeng** [comment]
It's the sample code's bug, when occurred  api error we should refresh UI to reset listview state.
Now fixed in f11a2bf90cda02a6dc33d2dc416f3ab30019e574
